---
extends: 
  - airbnb-base
  - prettier

env:
  node: true

globals:
  $: true
  videojs: true

plugins: 
  - prettier

rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: "es5"  
  no-unused-vars: 
    - error
    - argsIgnorePattern: next
...